version: '3'
services:
  sts:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./env:/app/env
      - ./model_pretrained:/app/model_pretrained
      - ./ffmpeg:/usr/bin/ffmpeg # 这样子就不要apt安装了
    environment:
      - LLM=chatgpt
      - TTS=cosy
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - PROMPT_AUDIO=model_pretrained/SenseVoiceSmall/example/zh.mp3
      - PROMPT_TEXT=开放时间，早上九点至下午五点
      - FRCRN_DEVICE=cpu
      - SENSE_DEVICE=cpu
    deploy: # 对于有gpu的设备，需要指定硬件
        resources:
            reservations:
                devices:
                  - driver: nvidia
                    count: 1
                    capabilities: [gpu]

